In [1]:
from nsw_property_sale_web_scrapping import *

In [2]:
df = run_nsw_sales_pipeline()

🆕 未发现本地仓库，将初始化构建。
🚀 开始处理历史 Annual 销售档案包...
📥 正在下载 1990 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1990.zip
📥 正在下载 1991 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1991.zip
📥 正在下载 1992 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1992.zip
📥 正在下载 1993 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1993.zip
📥 正在下载 1994 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1994.zip
📥 正在下载 1995 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1995.zip
📥 正在下载 1996 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1996.zip
📥 正在下载 1997 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1997.zip
📥 正在下载 1998 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1998.zip
📥 正在下载 1999 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/1999.zip
📥 正在下载 2000 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2000.zip
📥 正在下载 2001 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2001.zip
📥 正在下载 2002 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2002.zip
📥 正在下载 2003 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2003.zip
📥 正在下载 2004 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2004.zip
📥 正在下载 2005 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2005.zip
📥 正在下载 2006 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2006.zip
📥 正在下载 2007 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2007.zip
📥 正在下载 2008 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2008.zip
📥 正在下载 2009 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2009.zip
📥 正在下载 2010 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2010.zip
📥 正在下载 2011 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2011.zip
📥 正在下载 2012 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2012.zip
📥 正在下载 2013 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2013.zip
📥 正在下载 2014 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2014.zip
📥 正在下载 2015 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2015.zip
   📦 正在剥离年包中的周数据: 20150105
   📦 正在剥离年包中的周数据: 20150112
   📦 正在剥离年包中的周数据: 20150119
   📦 正在剥离年包中的周数据: 20150126
   📦 正在剥离年包中的周数据: 20150202
   📦 正在剥离年包中的周数据: 20150209
   📦 正在剥离年包中的周数据: 20150216
   📦 正在剥离年包中的周数据: 20150223
   📦 正在剥离年包中的周数据: 20150302
   📦 正在剥离年包中的周数据: 20150309
   📦 正在剥离年包中的周数据: 20150316
   📦 正在剥离年包中的周数据: 20150323
   📦 正在剥离年包中的周数据: 20150330
   📦 正在剥离年包中的周数据: 20150406
   📦 正在剥离年包中的周数据: 20150413
   📦 正在剥离年包中的周数据: 20150420
   📦 正在剥离年包中的周数据: 20150427
   📦 正在剥离年包中的周数据: 20150504
   📦 正在剥离年包中的周数据: 20150511
   📦 正在剥离年包中的周数据: 20150518
   📦 正在剥离年包中的周数据: 20150525
   📦 正在剥离年包中的周数据: 20150601
   📦 正在剥离年包中的周数据: 20150608
   📦 正在剥离年包中的周数据: 20150615
   📦 正在剥离年包中的周数据: 20150622
   📦 正在剥离年包中的周数据: 20150629
   📦 正在剥离年包中的周数据: 20150630
   📦 正在剥离年包中的周数据: 20150706
   📦 正在剥离年包中的周数据: 20150713
   📦 正在剥离年包中的周数据: 20150720
   📦 正在剥离年包中的周数据: 20150727
   📦 正在剥离年包中的周数据: 20150803
   📦 正在剥离年包中的周数据: 20150810
   📦 正在剥离年包中的周数据: 20150817
   📦 正在剥离年包中的周数据: 20150824
   📦 正在剥离年包中的周数据: 20150831
   📦 正在剥离年包中的周数据: 20150907
   📦 正在剥离年包中的周数据: 20150914
   📦 正在剥离年包中的周数据: 20150921
   📦 正在剥离年包中的周数据: 20150928
   📦 正在剥离年包中的周数据: 20151005
   📦 正在剥离年包中的周数据: 20151012
   📦 正在剥离年包中的周数据: 20151019
   📦 正在剥离年包中的周数据: 20151026
   📦 正在剥离年包中的周数据: 20151102
   📦 正在剥离年包中的周数据: 20151109
   📦 正在剥离年包中的周数据: 20151116
   📦 正在剥离年包中的周数据: 20151123
   📦 正在剥离年包中的周数据: 20151130
   📦 正在剥离年包中的周数据: 20151207
   📦 正在剥离年包中的周数据: 20151214
   📦 正在剥离年包中的周数据: 20151221
   📦 正在剥离年包中的周数据: 20151228
📥 正在下载 2016 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2016.zip
   📦 正在剥离年包中的周数据: 20160104
   📦 正在剥离年包中的周数据: 20160111
   📦 正在剥离年包中的周数据: 20160118
   📦 正在剥离年包中的周数据: 20160125
   📦 正在剥离年包中的周数据: 20160201
   📦 正在剥离年包中的周数据: 20160208
   📦 正在剥离年包中的周数据: 20160215
   📦 正在剥离年包中的周数据: 20160222
   📦 正在剥离年包中的周数据: 20160229
   📦 正在剥离年包中的周数据: 20160307
   📦 正在剥离年包中的周数据: 20160314
   📦 正在剥离年包中的周数据: 20160321
   📦 正在剥离年包中的周数据: 20160328
   📦 正在剥离年包中的周数据: 20160404
   📦 正在剥离年包中的周数据: 20160411
   📦 正在剥离年包中的周数据: 20160418
   📦 正在剥离年包中的周数据: 20160425
   📦 正在剥离年包中的周数据: 20160502
   📦 正在剥离年包中的周数据: 20160509
   📦 正在剥离年包中的周数据: 20160516
   📦 正在剥离年包中的周数据: 20160523
   📦 正在剥离年包中的周数据: 20160530
   📦 正在剥离年包中的周数据: 20160606
   📦 正在剥离年包中的周数据: 20160613
   📦 正在剥离年包中的周数据: 20160620
   📦 正在剥离年包中的周数据: 20160627
   📦 正在剥离年包中的周数据: 20160704
   📦 正在剥离年包中的周数据: 20160711
   📦 正在剥离年包中的周数据: 20160718
   📦 正在剥离年包中的周数据: 20160725
   📦 正在剥离年包中的周数据: 20160801
   📦 正在剥离年包中的周数据: 20160808
   📦 正在剥离年包中的周数据: 20160815
   📦 正在剥离年包中的周数据: 20160822
   📦 正在剥离年包中的周数据: 20160829
   📦 正在剥离年包中的周数据: 20160905
   📦 正在剥离年包中的周数据: 20160912
   📦 正在剥离年包中的周数据: 20160919
   📦 正在剥离年包中的周数据: 20160926
   📦 正在剥离年包中的周数据: 20161003
   📦 正在剥离年包中的周数据: 20161010
   📦 正在剥离年包中的周数据: 20161017
   📦 正在剥离年包中的周数据: 20161024
   📦 正在剥离年包中的周数据: 20161031
   📦 正在剥离年包中的周数据: 20161107
   📦 正在剥离年包中的周数据: 20161114
   📦 正在剥离年包中的周数据: 20161121
   📦 正在剥离年包中的周数据: 20161128
   📦 正在剥离年包中的周数据: 20161205
   📦 正在剥离年包中的周数据: 20161212
   📦 正在剥离年包中的周数据: 20161219
   📦 正在剥离年包中的周数据: 20161226
📥 正在下载 2017 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2017.zip
   📦 正在剥离年包中的周数据: 20170102
   📦 正在剥离年包中的周数据: 20170109
   📦 正在剥离年包中的周数据: 20170116
   📦 正在剥离年包中的周数据: 20170123
   📦 正在剥离年包中的周数据: 20170130
   📦 正在剥离年包中的周数据: 20170206
   📦 正在剥离年包中的周数据: 20170213
   📦 正在剥离年包中的周数据: 20170220
   📦 正在剥离年包中的周数据: 20170227
   📦 正在剥离年包中的周数据: 20170306
   📦 正在剥离年包中的周数据: 20170313
   📦 正在剥离年包中的周数据: 20170320
   📦 正在剥离年包中的周数据: 20170327
   📦 正在剥离年包中的周数据: 20170403
   📦 正在剥离年包中的周数据: 20170410
   📦 正在剥离年包中的周数据: 20170417
   📦 正在剥离年包中的周数据: 20170424
   📦 正在剥离年包中的周数据: 20170501
   📦 正在剥离年包中的周数据: 20170508
   📦 正在剥离年包中的周数据: 20170515
   📦 正在剥离年包中的周数据: 20170522
   📦 正在剥离年包中的周数据: 20170529
   📦 正在剥离年包中的周数据: 20170605
   📦 正在剥离年包中的周数据: 20170612
   📦 正在剥离年包中的周数据: 20170619
   📦 正在剥离年包中的周数据: 20170626
   📦 正在剥离年包中的周数据: 20170703
   📦 正在剥离年包中的周数据: 20170710
   📦 正在剥离年包中的周数据: 20170717
   📦 正在剥离年包中的周数据: 20170724
   📦 正在剥离年包中的周数据: 20170731
   📦 正在剥离年包中的周数据: 20170807
   📦 正在剥离年包中的周数据: 20170814
   📦 正在剥离年包中的周数据: 20170821
   📦 正在剥离年包中的周数据: 20170828
   📦 正在剥离年包中的周数据: 20170904
   📦 正在剥离年包中的周数据: 20170911
   📦 正在剥离年包中的周数据: 20170918
   📦 正在剥离年包中的周数据: 20170925
   📦 正在剥离年包中的周数据: 20171002
   📦 正在剥离年包中的周数据: 20171009
   📦 正在剥离年包中的周数据: 20171016
   📦 正在剥离年包中的周数据: 20171023
   📦 正在剥离年包中的周数据: 20171030
   📦 正在剥离年包中的周数据: 20171106
   📦 正在剥离年包中的周数据: 20171113
   📦 正在剥离年包中的周数据: 20171120
   📦 正在剥离年包中的周数据: 20171127
   📦 正在剥离年包中的周数据: 20171204
   📦 正在剥离年包中的周数据: 20171211
   📦 正在剥离年包中的周数据: 20171218
   📦 正在剥离年包中的周数据: 20171225
📥 正在下载 2018 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2018.zip
   📦 正在剥离年包中的周数据: 20180115
   📦 正在剥离年包中的周数据: 20180122
   📦 正在剥离年包中的周数据: 20180129
   📦 正在剥离年包中的周数据: 20180205
   📦 正在剥离年包中的周数据: 20180212
   📦 正在剥离年包中的周数据: 20180219
   📦 正在剥离年包中的周数据: 20180226
   📦 正在剥离年包中的周数据: 20180305
   📦 正在剥离年包中的周数据: 20180312
   📦 正在剥离年包中的周数据: 20180319
   📦 正在剥离年包中的周数据: 20180326
   📦 正在剥离年包中的周数据: 20180402
   📦 正在剥离年包中的周数据: 20180409
   📦 正在剥离年包中的周数据: 20180416
   📦 正在剥离年包中的周数据: 20180423
   📦 正在剥离年包中的周数据: 20180430
   📦 正在剥离年包中的周数据: 20180507
   📦 正在剥离年包中的周数据: 20180514
   📦 正在剥离年包中的周数据: 20180521
   📦 正在剥离年包中的周数据: 20180528
   📦 正在剥离年包中的周数据: 20180604
   📦 正在剥离年包中的周数据: 20180611
   📦 正在剥离年包中的周数据: 20180618
   📦 正在剥离年包中的周数据: 20180625
   📦 正在剥离年包中的周数据: 20180702
   📦 正在剥离年包中的周数据: 20180709
   📦 正在剥离年包中的周数据: 20180716
   📦 正在剥离年包中的周数据: 20180723
   📦 正在剥离年包中的周数据: 20180730
   📦 正在剥离年包中的周数据: 20180806
   📦 正在剥离年包中的周数据: 20180813
   📦 正在剥离年包中的周数据: 20180820
   📦 正在剥离年包中的周数据: 20180827
   📦 正在剥离年包中的周数据: 20180903
   📦 正在剥离年包中的周数据: 20180910
   📦 正在剥离年包中的周数据: 20180917
   📦 正在剥离年包中的周数据: 20180924
   📦 正在剥离年包中的周数据: 20181001
   📦 正在剥离年包中的周数据: 20181008
   📦 正在剥离年包中的周数据: 20181015
   📦 正在剥离年包中的周数据: 20181022
   📦 正在剥离年包中的周数据: 20181029
   📦 正在剥离年包中的周数据: 20181105
   📦 正在剥离年包中的周数据: 20181112
   📦 正在剥离年包中的周数据: 20181119
   📦 正在剥离年包中的周数据: 20181126
   📦 正在剥离年包中的周数据: 20181203
   📦 正在剥离年包中的周数据: 20181210
   📦 正在剥离年包中的周数据: 20181217
   📦 正在剥离年包中的周数据: 20181224
   📦 正在剥离年包中的周数据: 20181231
📥 正在下载 2019 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2019.zip
   📦 正在剥离年包中的周数据: 20190107
   📦 正在剥离年包中的周数据: 20190114
   📦 正在剥离年包中的周数据: 20190121
   📦 正在剥离年包中的周数据: 20190128
   📦 正在剥离年包中的周数据: 20190204
   📦 正在剥离年包中的周数据: 20190211
   📦 正在剥离年包中的周数据: 20190218
   📦 正在剥离年包中的周数据: 20190225
   📦 正在剥离年包中的周数据: 20190304
   📦 正在剥离年包中的周数据: 20190311
   📦 正在剥离年包中的周数据: 20190318
   📦 正在剥离年包中的周数据: 20190325
   📦 正在剥离年包中的周数据: 20190401
   📦 正在剥离年包中的周数据: 20190408
   📦 正在剥离年包中的周数据: 20190415
   📦 正在剥离年包中的周数据: 20190422
   📦 正在剥离年包中的周数据: 20190429
   📦 正在剥离年包中的周数据: 20190506
   📦 正在剥离年包中的周数据: 20190513
   📦 正在剥离年包中的周数据: 20190520
   📦 正在剥离年包中的周数据: 20190527
   📦 正在剥离年包中的周数据: 20190603
   📦 正在剥离年包中的周数据: 20190610
   📦 正在剥离年包中的周数据: 20190617
   📦 正在剥离年包中的周数据: 20190624
   📦 正在剥离年包中的周数据: 20190701
   📦 正在剥离年包中的周数据: 20190708
   📦 正在剥离年包中的周数据: 20190715
   📦 正在剥离年包中的周数据: 20190722
   📦 正在剥离年包中的周数据: 20190729
   📦 正在剥离年包中的周数据: 20190805
   📦 正在剥离年包中的周数据: 20190812
   📦 正在剥离年包中的周数据: 20190819
   📦 正在剥离年包中的周数据: 20190826
   📦 正在剥离年包中的周数据: 20190902
   📦 正在剥离年包中的周数据: 20190909
   📦 正在剥离年包中的周数据: 20190916
   📦 正在剥离年包中的周数据: 20190923
   📦 正在剥离年包中的周数据: 20190930
   📦 正在剥离年包中的周数据: 20191007
   📦 正在剥离年包中的周数据: 20191014
   📦 正在剥离年包中的周数据: 20191021
   📦 正在剥离年包中的周数据: 20191028
   📦 正在剥离年包中的周数据: 20191104
   📦 正在剥离年包中的周数据: 20191111
   📦 正在剥离年包中的周数据: 20191118
   📦 正在剥离年包中的周数据: 20191125
   📦 正在剥离年包中的周数据: 20191202
   📦 正在剥离年包中的周数据: 20191209
   📦 正在剥离年包中的周数据: 20191216
   📦 正在剥离年包中的周数据: 20191223
   📦 正在剥离年包中的周数据: 20191230
📥 正在下载 2020 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2020.zip
   📦 正在剥离年包中的周数据: 20200106
   📦 正在剥离年包中的周数据: 20200113
   📦 正在剥离年包中的周数据: 20200120
   📦 正在剥离年包中的周数据: 20200127
   📦 正在剥离年包中的周数据: 20200203
   📦 正在剥离年包中的周数据: 20200210
   📦 正在剥离年包中的周数据: 20200217
   📦 正在剥离年包中的周数据: 20200224
   📦 正在剥离年包中的周数据: 20200302
   📦 正在剥离年包中的周数据: 20200309
   📦 正在剥离年包中的周数据: 20200316
   📦 正在剥离年包中的周数据: 20200323
   📦 正在剥离年包中的周数据: 20200330
   📦 正在剥离年包中的周数据: 20200406
   📦 正在剥离年包中的周数据: 20200413
   📦 正在剥离年包中的周数据: 20200420
   📦 正在剥离年包中的周数据: 20200427
   📦 正在剥离年包中的周数据: 20200504
   📦 正在剥离年包中的周数据: 20200511
   📦 正在剥离年包中的周数据: 20200518
   📦 正在剥离年包中的周数据: 20200525
   📦 正在剥离年包中的周数据: 20200601
   📦 正在剥离年包中的周数据: 20200608
   📦 正在剥离年包中的周数据: 20200615
   📦 正在剥离年包中的周数据: 20200622
   📦 正在剥离年包中的周数据: 20200629
   📦 正在剥离年包中的周数据: 20200706
   📦 正在剥离年包中的周数据: 20200713
   📦 正在剥离年包中的周数据: 20200720
   📦 正在剥离年包中的周数据: 20200727
   📦 正在剥离年包中的周数据: 20200803
   📦 正在剥离年包中的周数据: 20200810
   📦 正在剥离年包中的周数据: 20200817
   📦 正在剥离年包中的周数据: 20200824
   📦 正在剥离年包中的周数据: 20200831
   📦 正在剥离年包中的周数据: 20200907
   📦 正在剥离年包中的周数据: 20200914
   📦 正在剥离年包中的周数据: 20200921
   📦 正在剥离年包中的周数据: 20200928
   📦 正在剥离年包中的周数据: 20201005
   📦 正在剥离年包中的周数据: 20201012
   📦 正在剥离年包中的周数据: 20201019
   📦 正在剥离年包中的周数据: 20201026
   📦 正在剥离年包中的周数据: 20201102
   📦 正在剥离年包中的周数据: 20201109
   📦 正在剥离年包中的周数据: 20201116
   📦 正在剥离年包中的周数据: 20201123
   📦 正在剥离年包中的周数据: 20201130
   📦 正在剥离年包中的周数据: 20201207
   📦 正在剥离年包中的周数据: 20201214
   📦 正在剥离年包中的周数据: 20201221
   📦 正在剥离年包中的周数据: 20201228
📥 正在下载 2021 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2021.zip
   📦 正在剥离年包中的周数据: 20210104
   📦 正在剥离年包中的周数据: 20210111
   📦 正在剥离年包中的周数据: 20210118
   📦 正在剥离年包中的周数据: 20210125
   📦 正在剥离年包中的周数据: 20210201
   📦 正在剥离年包中的周数据: 20210208
   📦 正在剥离年包中的周数据: 20210215
   📦 正在剥离年包中的周数据: 20210222
   📦 正在剥离年包中的周数据: 20210301
   📦 正在剥离年包中的周数据: 20210308
   📦 正在剥离年包中的周数据: 20210315
   📦 正在剥离年包中的周数据: 20210322
   📦 正在剥离年包中的周数据: 20210329
   📦 正在剥离年包中的周数据: 20210405
   📦 正在剥离年包中的周数据: 20210412
   📦 正在剥离年包中的周数据: 20210419
   📦 正在剥离年包中的周数据: 20210426
   📦 正在剥离年包中的周数据: 20210503
   📦 正在剥离年包中的周数据: 20210510
   📦 正在剥离年包中的周数据: 20210517
   📦 正在剥离年包中的周数据: 20210524
   📦 正在剥离年包中的周数据: 20210531
   📦 正在剥离年包中的周数据: 20210607
   📦 正在剥离年包中的周数据: 20210614
   📦 正在剥离年包中的周数据: 20210621
   📦 正在剥离年包中的周数据: 20210628
   📦 正在剥离年包中的周数据: 20210705
   📦 正在剥离年包中的周数据: 20210712
   📦 正在剥离年包中的周数据: 20210719
   📦 正在剥离年包中的周数据: 20210726
   📦 正在剥离年包中的周数据: 20210802
   📦 正在剥离年包中的周数据: 20210809
   📦 正在剥离年包中的周数据: 20210816
   📦 正在剥离年包中的周数据: 20210823
   📦 正在剥离年包中的周数据: 20210830
   📦 正在剥离年包中的周数据: 20210906
   📦 正在剥离年包中的周数据: 20210913
   📦 正在剥离年包中的周数据: 20210920
   📦 正在剥离年包中的周数据: 20210927
   📦 正在剥离年包中的周数据: 20211004
   📦 正在剥离年包中的周数据: 20211011
   📦 正在剥离年包中的周数据: 20211018
   📦 正在剥离年包中的周数据: 20211025
   📦 正在剥离年包中的周数据: 20211101
   📦 正在剥离年包中的周数据: 20211108
   📦 正在剥离年包中的周数据: 20211115
   📦 正在剥离年包中的周数据: 20211122
   📦 正在剥离年包中的周数据: 20211129
   📦 正在剥离年包中的周数据: 20211206
   📦 正在剥离年包中的周数据: 20211213
   📦 正在剥离年包中的周数据: 20211220
   📦 正在剥离年包中的周数据: 20211227
📥 正在下载 2022 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2022.zip
   📦 正在剥离年包中的周数据: 20220103
   📦 正在剥离年包中的周数据: 20220110
   📦 正在剥离年包中的周数据: 20220117
   📦 正在剥离年包中的周数据: 20220124
   📦 正在剥离年包中的周数据: 20220131
   📦 正在剥离年包中的周数据: 20220207
   📦 正在剥离年包中的周数据: 20220214
   📦 正在剥离年包中的周数据: 20220221
   📦 正在剥离年包中的周数据: 20220228
   📦 正在剥离年包中的周数据: 20220307
   📦 正在剥离年包中的周数据: 20220314
   📦 正在剥离年包中的周数据: 20220321
   📦 正在剥离年包中的周数据: 20220328
   📦 正在剥离年包中的周数据: 20220404
   📦 正在剥离年包中的周数据: 20220411
   📦 正在剥离年包中的周数据: 20220418
   📦 正在剥离年包中的周数据: 20220425
   📦 正在剥离年包中的周数据: 20220502
   📦 正在剥离年包中的周数据: 20220509
   📦 正在剥离年包中的周数据: 20220516
   📦 正在剥离年包中的周数据: 20220523
   📦 正在剥离年包中的周数据: 20220530
   📦 正在剥离年包中的周数据: 20220606
   📦 正在剥离年包中的周数据: 20220613
   📦 正在剥离年包中的周数据: 20220620
   📦 正在剥离年包中的周数据: 20220627
   📦 正在剥离年包中的周数据: 20220704
   📦 正在剥离年包中的周数据: 20220711
   📦 正在剥离年包中的周数据: 20220718
   📦 正在剥离年包中的周数据: 20220725
   📦 正在剥离年包中的周数据: 20220801
   📦 正在剥离年包中的周数据: 20220808
   📦 正在剥离年包中的周数据: 20220815
   📦 正在剥离年包中的周数据: 20220822
   📦 正在剥离年包中的周数据: 20220829
   📦 正在剥离年包中的周数据: 20220905
   📦 正在剥离年包中的周数据: 20220912
   📦 正在剥离年包中的周数据: 20220919
   📦 正在剥离年包中的周数据: 20220926
   📦 正在剥离年包中的周数据: 20221003
   📦 正在剥离年包中的周数据: 20221010
   📦 正在剥离年包中的周数据: 20221017
   📦 正在剥离年包中的周数据: 20221024
   📦 正在剥离年包中的周数据: 20221031
   📦 正在剥离年包中的周数据: 20221107
   📦 正在剥离年包中的周数据: 20221114
   📦 正在剥离年包中的周数据: 20221121
   📦 正在剥离年包中的周数据: 20221128
   📦 正在剥离年包中的周数据: 20221205
   📦 正在剥离年包中的周数据: 20221212
   📦 正在剥离年包中的周数据: 20221219
   📦 正在剥离年包中的周数据: 20221226
📥 正在下载 2023 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2023.zip
   📦 正在剥离年包中的周数据: 20230102
   📦 正在剥离年包中的周数据: 20230109
   📦 正在剥离年包中的周数据: 20230116
   📦 正在剥离年包中的周数据: 20230123
   📦 正在剥离年包中的周数据: 20230130
   📦 正在剥离年包中的周数据: 20230206
   📦 正在剥离年包中的周数据: 20230213
   📦 正在剥离年包中的周数据: 20230220
   📦 正在剥离年包中的周数据: 20230227
   📦 正在剥离年包中的周数据: 20230306
   📦 正在剥离年包中的周数据: 20230313
   📦 正在剥离年包中的周数据: 20230320
   📦 正在剥离年包中的周数据: 20230327
   📦 正在剥离年包中的周数据: 20230403
   📦 正在剥离年包中的周数据: 20230410
   📦 正在剥离年包中的周数据: 20230417
   📦 正在剥离年包中的周数据: 20230424
   📦 正在剥离年包中的周数据: 20230501
   📦 正在剥离年包中的周数据: 20230508
   📦 正在剥离年包中的周数据: 20230515
   📦 正在剥离年包中的周数据: 20230522
   📦 正在剥离年包中的周数据: 20230529
   📦 正在剥离年包中的周数据: 20230605
   📦 正在剥离年包中的周数据: 20230612
   📦 正在剥离年包中的周数据: 20230619
   📦 正在剥离年包中的周数据: 20230626
   📦 正在剥离年包中的周数据: 20230703
   📦 正在剥离年包中的周数据: 20230710
   📦 正在剥离年包中的周数据: 20230717
   📦 正在剥离年包中的周数据: 20230724
   📦 正在剥离年包中的周数据: 20230731
   📦 正在剥离年包中的周数据: 20230807
   📦 正在剥离年包中的周数据: 20230814
   📦 正在剥离年包中的周数据: 20230821
   📦 正在剥离年包中的周数据: 20230828
   📦 正在剥离年包中的周数据: 20230904
   📦 正在剥离年包中的周数据: 20230911
   📦 正在剥离年包中的周数据: 20230918
   📦 正在剥离年包中的周数据: 20230925
   📦 正在剥离年包中的周数据: 20231002
   📦 正在剥离年包中的周数据: 20231009
   📦 正在剥离年包中的周数据: 20231016
   📦 正在剥离年包中的周数据: 20231023
   📦 正在剥离年包中的周数据: 20231030
   📦 正在剥离年包中的周数据: 20231106
   📦 正在剥离年包中的周数据: 20231113
   📦 正在剥离年包中的周数据: 20231120
   📦 正在剥离年包中的周数据: 20231127
   📦 正在剥离年包中的周数据: 20231204
   📦 正在剥离年包中的周数据: 20231211
   📦 正在剥离年包中的周数据: 20231218
   📦 正在剥离年包中的周数据: 20231225
📥 正在下载 2024 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2024.zip
   📦 正在剥离年包中的周数据: 20240101
   📦 正在剥离年包中的周数据: 20240108
   📦 正在剥离年包中的周数据: 20240115
   📦 正在剥离年包中的周数据: 20240122
   📦 正在剥离年包中的周数据: 20240129
   📦 正在剥离年包中的周数据: 20240205
   📦 正在剥离年包中的周数据: 20240212
   📦 正在剥离年包中的周数据: 20240219
   📦 正在剥离年包中的周数据: 20240226
   📦 正在剥离年包中的周数据: 20240304
   📦 正在剥离年包中的周数据: 20240311
   📦 正在剥离年包中的周数据: 20240318
   📦 正在剥离年包中的周数据: 20240325
   📦 正在剥离年包中的周数据: 20240401
   📦 正在剥离年包中的周数据: 20240408
   📦 正在剥离年包中的周数据: 20240415
   📦 正在剥离年包中的周数据: 20240422
   📦 正在剥离年包中的周数据: 20240429
   📦 正在剥离年包中的周数据: 20240506
   📦 正在剥离年包中的周数据: 20240513
   📦 正在剥离年包中的周数据: 20240520
   📦 正在剥离年包中的周数据: 20240527
   📦 正在剥离年包中的周数据: 20240603
   📦 正在剥离年包中的周数据: 20240610
   📦 正在剥离年包中的周数据: 20240617
   📦 正在剥离年包中的周数据: 20240624
   📦 正在剥离年包中的周数据: 20240701
   📦 正在剥离年包中的周数据: 20240708
   📦 正在剥离年包中的周数据: 20240715
   📦 正在剥离年包中的周数据: 20240722
   📦 正在剥离年包中的周数据: 20240729
   📦 正在剥离年包中的周数据: 20240805
   📦 正在剥离年包中的周数据: 20240812
   📦 正在剥离年包中的周数据: 20240819
   📦 正在剥离年包中的周数据: 20240826
   📦 正在剥离年包中的周数据: 20240902
   📦 正在剥离年包中的周数据: 20240909
   📦 正在剥离年包中的周数据: 20240916
   📦 正在剥离年包中的周数据: 20240923
   📦 正在剥离年包中的周数据: 20240930
   📦 正在剥离年包中的周数据: 20241007
   📦 正在剥离年包中的周数据: 20241014
   📦 正在剥离年包中的周数据: 20241021
   📦 正在剥离年包中的周数据: 20241028
   📦 正在剥离年包中的周数据: 20241104
   📦 正在剥离年包中的周数据: 20241111
   📦 正在剥离年包中的周数据: 20241118
   📦 正在剥离年包中的周数据: 20241125
   📦 正在剥离年包中的周数据: 20241202
   📦 正在剥离年包中的周数据: 20241209
   📦 正在剥离年包中的周数据: 20241216
   📦 正在剥离年包中的周数据: 20241223
   📦 正在剥离年包中的周数据: 20241230
📥 正在下载 2025 全年大包: https://www.valuergeneral.nsw.gov.au/__psi/yearly/2025.zip
   📦 正在剥离年包中的周数据: 20250106
   📦 正在剥离年包中的周数据: 20250113
   📦 正在剥离年包中的周数据: 20250120
   📦 正在剥离年包中的周数据: 20250127
   📦 正在剥离年包中的周数据: 20250203
   📦 正在剥离年包中的周数据: 20250210
   📦 正在剥离年包中的周数据: 20250217
   📦 正在剥离年包中的周数据: 20250224
   📦 正在剥离年包中的周数据: 20250303
   📦 正在剥离年包中的周数据: 20250310
   📦 正在剥离年包中的周数据: 20250317
   📦 正在剥离年包中的周数据: 20250324
   📦 正在剥离年包中的周数据: 20250331
   📦 正在剥离年包中的周数据: 20250407
   📦 正在剥离年包中的周数据: 20250414
   📦 正在剥离年包中的周数据: 20250421
   📦 正在剥离年包中的周数据: 20250428
   📦 正在剥离年包中的周数据: 20250505
   📦 正在剥离年包中的周数据: 20250512
   📦 正在剥离年包中的周数据: 20250519
   📦 正在剥离年包中的周数据: 20250526
   📦 正在剥离年包中的周数据: 20250602
   📦 正在剥离年包中的周数据: 20250609
   📦 正在剥离年包中的周数据: 20250616
   📦 正在剥离年包中的周数据: 20250623
   📦 正在剥离年包中的周数据: 20250630
   📦 正在剥离年包中的周数据: 20250707
   📦 正在剥离年包中的周数据: 20250714
   📦 正在剥离年包中的周数据: 20250721
   📦 正在剥离年包中的周数据: 20250728
   📦 正在剥离年包中的周数据: 20250804
   📦 正在剥离年包中的周数据: 20250811
   📦 正在剥离年包中的周数据: 20250818
   📦 正在剥离年包中的周数据: 20250825
   📦 正在剥离年包中的周数据: 20250901
   📦 正在剥离年包中的周数据: 20250908
   📦 正在剥离年包中的周数据: 20250915
   📦 正在剥离年包中的周数据: 20250922
   📦 正在剥离年包中的周数据: 20250929
   📦 正在剥离年包中的周数据: 20251006
   📦 正在剥离年包中的周数据: 20251013
   📦 正在剥离年包中的周数据: 20251020
   📦 正在剥离年包中的周数据: 20251027
   📦 正在剥离年包中的周数据: 20251103
   📦 正在剥离年包中的周数据: 20251110
   📦 正在剥离年包中的周数据: 20251117
   📦 正在剥离年包中的周数据: 20251124
   📦 正在剥离年包中的周数据: 20251201
   📦 正在剥离年包中的周数据: 20251208
   📦 正在剥离年包中的周数据: 20251215
   📦 正在剥离年包中的周数据: 20251222
   📦 正在剥离年包中的周数据: 20251229
🚀 扫描网页最新的 Weekly 增量更新区...
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260105.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260112.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260119.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260126.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260202.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260209.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260216.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260223.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260302.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260309.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260316.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260323.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260330.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260406.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260413.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260420.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260427.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260504.zip
📥 发现新周数据！正在捕获: https://www.valuergeneral.nsw.gov.au/__psi/weekly/20260511.zip
🎉 成功持久化到本地！当前仓库总行数: 2479311
🗑️ 临时文件夹已被完全强制粉碎。

In [5]:
df.head()

,property_id,house_number,street_name,suburb,postcode,area,area_unit,contract_date,settlement_date,sale_price,zone,property_type,lot_description,source_week
0,3372909,16,BRANDIS ST,ABERDARE,2325,256.0,M,2014-11-05,2014-12-12,265000.0,R2,RESIDENCE,122/1122749,20150105
1,3054011,,MYRTLE ACCS,CESSNOCK,2325,1197.0,M,2014-11-24,2014-12-23,95000.0,R2,VACANT LAND,83/270158,20150105
2,30493,25,BARRENJOEY RD,ETTALONG BEACH,2257,518.5,M,2014-11-20,2014-12-12,425000.0,R1,RESIDENCE,9/O/9391,20150105
3,29028,34,AVOCA DR,AVOCA BEACH,2251,NaN,,2014-10-03,2014-11-07,550000.0,,RESIDENCE,4/SP35156,20150105
4,37579,12,CANTERBURY CL,TERRIGAL,2260,450.0,M,2014-09-04,2014-12-12,635000.0,R2,RESIDENCE,27/861885,20150105

In [4]:
df.shape

(2479311, 14)

In [24]:
df['year'] = df.settlement_date.dt.year

In [40]:
td = df[df.year > 2020]

In [41]:
ttd = td[td.area > 100][td.area < 150][td.sale_price < 800000]

/var/folders/tq/bpv_y9gj4fb6mdryd1tdgnv00000gn/T/ipykernel_3259/3757958661.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ttd = td[td.area > 100][td.area < 150][td.sale_price < 800000]
/var/folders/tq/bpv_y9gj4fb6mdryd1tdgnv00000gn/T/ipykernel_3259/3757958661.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  ttd = td[td.area > 100][td.area < 150][td.sale_price < 800000]

In [42]:
ttd.suburb.unique().tolist()

['NORWEST',
 'THORNLEIGH',
 'SHELLHARBOUR CITY CENTRE',
 'HOMEBUSH',
 'COFFS HARBOUR',
 'BONNYRIGG',
 'WARWICK FARM',
 'WENTWORTH POINT',
 'PARRAMATTA',
 'ASHFIELD',
 'EDGEWORTH',
 'CHARLESTOWN',
 'ALBURY',
 'ASQUITH',
 'GERRINGONG',
 'LAKE ILLAWARRA',
 'OAK FLATS',
 'MITTAGONG',
 'WOLLONGONG',
 'HOMEBUSH WEST',
 'STRATHFIELD',
 'WOOLOOWARE',
 'JANNALI',
 'TWEED HEADS',
 'MOUNT DRUITT',
 'BARDIA',
 'EDMONDSON PARK',
 'PENRITH',
 'BANKSTOWN',
 'HURLSTONE PARK',
 'GREENACRE',
 'GOSFORD',
 'WOY WOY',
 'WESTMEAD',
 'NORTHMEAD',
 'CARLINGFORD',
 'LIDCOMBE',
 'GRANVILLE',
 'MAYS HILL',
 'HURSTVILLE',
 'KINGSGROVE',
 'PEAKHURST',
 'RAMSGATE',
 'CROYDON',
 'BULLIAC',
 'BELROSE',
 'CROMER',
 'QUEANBEYAN',
 'ARNCLIFFE',
 'RUSHCUTTERS BAY',
 'WARNERS BAY',
 'MORISSET',
 'BLACKALLS PARK',
 'MAYFIELD WEST',
 'ELERMORE VALE',
 'DURAL',
 'BAULKHAM HILLS',
 'KELLYVILLE',
 'NORTH KELLYVILLE',
 'HORNSBY',
 'WAITARA',
 'MEADOWBANK',
 'CANYONLEIGH',
 'DAPTO',
 'CROYDON PARK',
 'STRATHFIELD SOUTH',
 'SUTHERLAND',
 'KIRRAWEE',
 'SOUTH WEST ROCKS',
 'KYOGLE',
 'BILAMBIL HEIGHTS',
 'BANORA POINT',
 'ROPES CROSSING',
 'SCHOFIELDS',
 'BLACKTOWN',
 'LEURA',
 'GREGORY HILLS',
 'CAMPBELLTOWN',
 'LIVERPOOL',
 'AUSTRAL',
 'ST MARYS',
 'URBENVILLE',
 'TENTERFIELD',
 'WALCHA',
 'LAKEMBA',
 'CAMPSIE',
 'CANTERBURY',
 'BELMORE',
 'CONSTITUTION HILL',
 'EPPING',
 'MELROSE PARK',
 'WENTWORTHVILLE',
 'TOONGABBIE',
 'AUBURN',
 'COOTAMUNDRA',
 'FORBES CREEK',
 'ROCKY PLAIN',
 'DUBBO',
 'CURRA CREEK',
 'WOLLI CREEK',
 'MASCOT',
 'BOTANY',
 'GLEN ELGIN',
 'GOULBURN',
 'ADAMSTOWN',
 'NEWCASTLE WEST',
 'ST IVES',
 'NORTH RYDE',
 'ALBION PARK',
 'SOUTH NOWRA',
 'MOSS VALE',
 'BULLI',
 'PARKES',
 'ENFIELD',
 'CARINGBAH',
 'BALLINA',
 'WOOLGOOLGA',
 'MARSDEN PARK',
 'CURRANS HILL',
 'JORDAN SPRINGS',
 'GLENMORE PARK',
 'BULLAWA CREEK',
 'EAST GOSFORD',
 'SYDNEY OLYMPIC PARK',
 'GUILDFORD',
 'PENDLE HILL',
 'MAYRUNG',
 'MARRICKVILLE',
 'FORSTER',
 'NUMBER ONE',
 'TUNCURRY',
 'ROCKDALE',
 'BATHURST',
 'WATERLOO',
 'ROSEBERY',
 'SPEERS POINT',
 'NEW LAMBTON',
 'GANMAIN',
 'BOMADERRY',
 'FAIRY MEADOW',
 'AUSTINMER',
 'RHODES',
 'BELFIELD',
 'HEATHCOTE',
 'KINGSCLIFF',
 'MAROUBRA',
 'QUAKERS HILL',
 'LURNEA',
 'KINGSWOOD',
 'NARWEE',
 'PUNCHBOWL',
 'CHESTER HILL',
 'POTTS HILL',
 'REVESBY',
 'MERRYLANDS',
 'MULWALA',
 'BLUEYS BEACH',
 'HILLSDALE',
 'BOTOBOLAR',
 'EAST TAMWORTH',
 'NORTH TAMWORTH',
 'ZETLAND',
 'CAMS WHARF',
 'PUTTY',
 'CANOWINDRA',
 'BURRAGA',
 'GYMEA',
 'ENGADINE',
 'LENNOX HEAD',
 'CHERRY TREE HILL',
 'VILLAWOOD',
 'RIVERWOOD',
 'THE ENTRANCE',
 'AVOCA BEACH',
 'ROSEHILL',
 'DENILIQUIN',
 'COOPLACURRIPA',
 'SOFALA',
 'ERUDGERE',
 'MEROTHERIE',
 'PORT MACQUARIE',
 'SOUTH TAMWORTH',
 'HUNTERS HILL',
 'RYDE',
 'GUYONG',
 'CRONULLA',
 'HAMMONDVILLE',
 'RYDALMERE',
 'CAMPERDOWN',
 'QUEANBEYAN WEST',
 'EAST WAGGA WAGGA',
 'GOWAN',
 'CAMBRA',
 'WHITEBRIDGE',
 'RUTHERFORD',
 'NEWCASTLE',
 'WICKHAM',
 'WARATAH WEST',
 'HAMILTON NORTH',
 'EAST ALBURY',
 'HANWOOD',
 'CASTLE HILL',
 'GLADESVILLE',
 'THIRROUL',
 'EAST BALLINA',
 'URUNGA',
 'MURWILLUMBAH',
 'TWEED HEADS WEST',
 'WILEY PARK',
 'BERKELEY VALE',
 'TERRIGAL',
 'BLIGHTY',
 'KOGARAH',
 'WARRIEWOOD',
 'TYRINGHAM',
 'MOUNT ROYAL',
 'PAMBULA',
 'CULBURRA BEACH',
 'PORT KEMBLA',
 'ALSTONVILLE',
 'SAWTELL',
 'ORAN PARK',
 'WINDSOR',
 'CARRAMAR',
 'MOOREBANK',
 'BASS HILL',
 'HARRIS PARK',
 'NORTH ROCKS',
 'DIAMOND BEACH',
 'ROYALLA',
 'BERRIDALE',
 'TOOMA',
 'APPLEBY',
 'WEST TAMWORTH',
 'ALEXANDRIA',
 'CARRINGTON',
 'MACQUARIE PARK',
 'ORANGE',
 'BREAKFAST POINT',
 'MIRANDA',
 'GRAMAN',
 'ROUSE HILL',
 'TAHMOOR',
 'GIRRAWEEN',
 'GUNDAGAI',
 'DULWICH HILL',
 'TEA GARDENS',
 'WHEELER HEIGHTS',
 'GOOGONG',
 'BANNABY',
 'ISLINGTON',
 'MOUNT COLAH',
 'LEWIS PONDS',
 'MULLUMBIMBY',
 'NORTH BOAMBEE VALLEY',
 'TWEED HEADS SOUTH',
 'CHINDERAH',
 'BLUE VALE',
 'KELLYVILLE RIDGE',
 'LEPPINGTON',
 'CASULA',
 'CONDOBOLIN',
 'THALGARRAH',
 'MORTDALE',
 'CARLTON',
 'TAREE',
 'BARHAM',
 'TURRELLA',
 'STOCKYARD CREEK',
 'ULMARRA',
 'TEMORA',
 'SURRY HILLS',
 'GOOLOOGONG',
 'BARRACK HEIGHTS',
 'CONISTON',
 'WOONONA',
 'BURWOOD',
 'LIBERTY GROVE',
 'WEST BALLINA',
 'WOLLONGBAR',
 'BOSTOBRICK',
 'KINGSFORD',
 'NORTH ST MARYS',
 'WEE WAA',
 'UPPER TOOLOOM',
 'ETTALONG BEACH',
 'WYONG',
 'WEST GOSFORD',
 'ANNANDALE',
 'TRIANGLE FLAT',
 'YARRABIN',
 'WALLSEND',
 'SWAN BAY',
 'WEST RYDE',
 'CORRIMAL',
 'LISMORE',
 'PROSPECT',
 'CAMDEN',
 'WARREN',
 'SEFTON',
 'WARNERVALE',
 'NORTH PARRAMATTA',
 'DEEPWATER',
 'WAGGA WAGGA',
 'NOWRA',
 'SAPPHIRE',
 'EARLWOOD',
 'MERRYLANDS WEST',
 'THURGOONA',
 'EASTWOOD',
 'TULLIMBAR',
 'ILLAWONG',
 'DAIRY FLAT',
 'DELUNGRA',
 'MACQUARIE FIELDS',
 'FAIRFIELD HEIGHTS',
 'TARRIARO',
 'EDGEROI',
 'BOLIVIA',
 'CHAIN VALLEY BAY',
 'BELBORA',
 'MOUNT GEORGE',
 'BIALA',
 'COONABARABRAN',
 'CARCALGONG',
 'CARDIFF',
 'MERIMBULA',
 'LEETON',
 'GORDON',
 'MENAI',
 'DENHAM COURT',
 'EAST HILLS',
 'YAGOONA',
 'ROSELANDS',
 'NORTH GOSFORD',
 'BARWANG',
 'BEXLEY NORTH',
 'EMMAVILLE',
 'ERSKINEVILLE',
 'TORONTO',
 'MAISON DIEU',
 'PERICOE',
 'MOSMAN',
 'MOZART',
 'BURWOOD HEIGHTS',
 'KALANG',
 'NEW ITALY',
 'FAIRFIELD WEST',
 'NOWENDOC',
 'ERINA',
 'TELOPEA',
 'ALLAWAH',
 'DODSWORTH',
 'EASTLAKES',
 'TORRINGTON',
 'MERRIWA',
 'ROSEWOOD',
 'LIMEKILNS',
 'BYABARRA',
 'BENNETTS GREEN',
 'LANE COVE',
 'ULLADULLA',
 'WOOLNERS ARM',
 'SEVEN HILLS',
 'JAMISONTOWN',
 'LOWER CREEK',
 'GOROKAN',
 'PETERSHAM',
 'MAFFRA',
 'MOUNT HUTTON',
 'LAVINGTON',
 'LANE COVE NORTH',
 'RANDWICK',
 'VAUCLUSE',
 'GLEDSWOOD HILLS',
 'FAIRFIELD',
 'KOREELAH',
 'GUYRA',
 'PENSHURST',
 'MURRUMBURRAH',
 'MOPPY',
 'MANLY',
 'MUMMEL',
 'KOORINGAL',
 'ROBIN HILL',
 'TURILL',
 'BELMONT',
 'BROOKLANA',
 'YARRAVEL',
 'BEVERLY HILLS',
 'MURRAY DOWNS',
 'CRESTWOOD',
 'NIMMO',
 'GLEN INNES',
 'MACLEAN',
 'TAYLORS BEACH',
 'CHATSWOOD',
 'KIAMA',
 'BRONTE',
 'SPRINGWOOD',
 'CAMDEN SOUTH',
 'EMU PLAINS',
 'NARROMINE',
 'TOOWOON BAY',
 'HILLVILLE',
 'CURRAWANG',
 'COOMA',
 'EUMUNGERIE',
 'NYMBOIDA',
 'BONNELLS BAY',
 'MAYFIELD',
 'NORTH WOLLONGONG',
 'TRUNDLE',
 'ALECTOWN',
 'MATRAVILLE',
 'NARELLAN',
 'INGLEBURN',
 'BATEAU BAY',
 'GREYSTANES',
 'COUNTEGANY',
 'BIGGA',
 'MITCHELL',
 'SALISBURY',
 'NORTH ALBURY',
 'TURRAMURRA',
 'FLINDERS',
 'ALBION PARK RAIL',
 'ROOTY HILL',
 'MEGALONG VALLEY',
 'LITHGOW',
 'OXLEY PARK',
 'TOMINGLEY',
 'BEXLEY',
 'WARIALDA',
 'IRONBARK',
 'KAHIBAH',
 'CHIPPING NORTON',
 'COLYTON',
 'CURBAN',
 'PEAKHURST HEIGHTS',
 'TIPPERARY',
 'SHANNONS FLAT',
 'MILA',
 'FINLEY',
 'SOUTH BALLINA',
 'CAMBRIDGE PARK',
 'FAIRHOLME',
 'ROCKY RIVER',
 'WOODSIDE',
 'PANANIA',
 'DRIPSTONE',
 'CUMBANDRY',
 'HARGRAVES',
 'DARLINGHURST',
 'SHORTLAND',
 'JESMOND',
 'PYMBLE',
 'NORTH DORRIGO',
 'YARROWYCK',
 'CLOVELLY',
 'RIVERSTONE',
 'POINT FREDERICK',
 'WINSTON HILLS',
 'WALLABI POINT',
 'TRALEE',
 'KANDOS',
 'NORTH HAVEN',
 'MEREWETHER',
 'SURF BEACH',
 'UTUNGUN',
 'JACKS CREEK',
 'COBARK',
 'TINDERRY',
 'SANDY CREEK',
 'CAVES BEACH',
 'MAITLAND',
 'BERMAGUI',
 'WYNDHAM',
 'TOCUMWAL',
 'KENTUCKY SOUTH',
 'MOAMA',
 'BROOKVALE',
 'FIVE DOCK',
 'NORTH STRATHFIELD',
 'NYNGAN',
 'SILENT GROVE',
 'BULLDOG',
 'BINNAWAY',
 'FREEMANTLE',
 'HAMILTON SOUTH',
 'HELENSBURGH',
 'ELLANGOWAN',
 'THUMB CREEK',
 'LITTLE BAY',
 'PADDINGTON',
 'BOGGABRI',
 'PADSTOW',
 'BOWMAN',
 'COOMBELL',
 'TINGHA',
 'THE MARRA',
 'SANS SOUCI',
 'FRESHWATER',
 'EASTGARDENS',
 'MATHESON',
 'THE JUNCTION',
 'WARATAH',
 'NELLIGEN',
 'SHELL COVE',
 'BOWENFELS',
 'TUGRABAKH',
 'UPPER ROUCHEL',
 'NEWTOWN',
 'ST LEONARDS',
 'FAIRFIELD EAST',
 'BLUE HAVEN',
 'TUGGERAH',
 'BOREE CREEK',
 'COOTRALANTRA',
 'QUIRINDI',
 'DALTON',
 'COWRA',
 'WARRAWEE',
 'ROWLANDS CREEK',
 'BACK CREEK',
 'WALGETT',
 'UMINA BEACH',
 'WOOTTON',
 'TUMUT',
 'INVERELL',
 'TURRAWAN',
 'SANDY FLAT',
 'CONARGO',
 'WHITLOW',
 'BARRETTS CREEK',
 'WOLLAR',
 'BUCKENBOWRA',
 'ISABELLA',
 'CONCORD',
 'MOREE',
 'ARMIDALE',
 'BARRATTA',
 'NORTH NARRABEEN',
 'QUEANBEYAN EAST',
 'KHANCOBAN',
 'HALLS CREEK',
 'SOUTH ALBURY',
 'OLD TOONGABBIE',
 'MOULAMEIN',
 'SNOWY PLAIN',
 'WAUCHOPE',
 'BARRABA',
 'WOODBERRY',
 'DRUMMOYNE',
 'COLLIE',
 'LISAROW',
 'POSSUM BRUSH',
 'COLEAMBALLY',
 'WOOMBAH',
 'COOKS HILL',
 'WARBURN',
 'GLEN ALICE',
 'NARRABRI',
 'BLUE BAY',
 'TOUKLEY',
 'KOGARAH BAY',
 'BLAXLANDS CREEK',
 'KURRI KURRI',
 'QUANDIALLA',
 'EAST KEMPSEY',
 'NULLAMANNA',
 'BONDI',
 'YARRIE LAKE',
 'TIMBARRA',
 'FORBES RIVER',
 'BEMBOKA',
 'EURONGILLY',
 'BELLA VISTA',
 'JEREMY',
 'CEDAR POINT',
 'BALALA',
 'SOMERSBY',
 'FAIRLIGHT',
 'ADAMINABY',
 'MOOKERAWA',
 'CARAGABAL',
 'BATEHAVEN',
 'BELLAMBI',
 'BOGAN GATE',
 'BOORABEE PARK',
 'ASHFORD',
 'KANIMBLA',
 'WYOMING',
 'SOUTH HURSTVILLE',
 'COOLONGOLOOK',
 'KRAWARREE',
 'WELAREGANG',
 'COOLAH',
 'TERALBA',
 'WARABROOK',
 'KANGAROO VALLEY',
 'BELLANGRY',
 'HAMILTON',
 'TANTAWANGALO',
 'BALDRY',
 'GINGKIN',
 'MOUNT ANNAN',
 'ANABRANCH SOUTH',
 'MOGGS SWAMP',
 'PIAMBONG',
 'CHISWICK',
 'GURLEY',
 'SCONE',
 'WEST BUNGAWALBIN',
 'MUNGINDI',
 'MOLE RIVER',
 'NULLO MOUNTAIN',
 'ELLENBOROUGH',
 'OURIMBAH',
 'BALMAIN',
 'NYORA',
 'JINDABYNE',
 'TALBINGO',
 'WEST ALBURY',
 'MORTLAKE',
 'CAPEEN CREEK',
 'WERRINGTON',
 'BOHENA CREEK',
 'WENTWORTH',
 'COROWA',
 'LOUISA CREEK',
 'ABERGLASSLYN',
 'MUSWELLBROOK',
 'DENISTONE',
 'HOGARTH RANGE',
 'GOONELLABAH',
 'DEE WHY',
 'GREENWICH',
 'NAREMBURN',
 'BURRIER',
 'BYRON BAY',
 'YABBRA',
 'SILVERWATER',
 'WELLINGROVE',
 'WATTLE FLAT',
 'UPPER PAPPINBARRA',
 'CESSNOCK',
 'FLETCHER',
 'MOLLYMOOK',
 'GIRRALONG',
 'CARTWRIGHT',
 'WEST WYALONG',
 'GEORGES HALL',
 'ST PETERS',
 'HAWKS NEST',
 'HARRINGTON',
 'HEREFORD HALL',
 'PAGEWOOD',
 'ROSE BAY',
 'TABULAM',
 'WAKOOL',
 'STANMORE',
 'CAPTAINS FLAT',
 'MARTINS CREEK',
 'YARRAWA',
 'BABYL CREEK',
 'FOREST LODGE',
 'COAL POINT',
 'MOPARRABAH',
 'NORTH BONDI',
 'YOUNG',
 'FIREFLY',
 'TUENA',
 'MUDGEE',
 'MILLERS POINT',
 'NARRANDERA',
 'NORTH NAROOMA',
 'MOUNT WARRIGAL',
 'KEMPS CREEK',
 'LONG JETTY',
 'WAUGORAH',
 'KALKITE',
 'FORTIS CREEK',
 'WATTON',
 'WINDEYER',
 'REDFERN',
 'LINDFIELD',
 'LAKE CONJOLA',
 'OPHIR',
 'KENSINGTON',
 'SMITHFIELD',
 'BALLADORAN',
 'WAITUI',
 'MARKS POINT',
 'SPRINGFIELD',
 'CANDELO',
 'BUMBALDRY',
 'CRABBES CREEK',
 'JEWS LAGOON',
 'TARAGO',
 'YARRAS',
 'STANBRIDGE',
 'TULLAKOOL',
 'DRY PLAIN',
 'JACKADGERY',
 'EAST CORRIMAL',
 'COOGEE',
 'BONDI JUNCTION',
 'BURRABOI',
 'DALGETY',
 'ARGALONG',
 'EUCHAREENA',
 'GRATTAI',
 'SYDNEY',
 'GARRA',
 'TULLAMORE',
 'KORORA',
 'BEECROFT',
 'HOLROYD',
 'BROADWAY',
 'CREMORNE',
 'COOKAMIDGERA',
 'MACQUARIE LINKS',
 'CATHCART',
 'BIBBENLUKE',
 'VALENTINE',
 'DUNDAS',
 'STUBBO',
 'MOUNT KURING-GAI',
 'RYDAL',
 'WALLERAWANG',
 'GLENREAGH',
 'EAST MAITLAND',
 'TWELVE MILE',
 'FIGTREE',
 'PAYTENS BRIDGE',
 'PALM BEACH',
 'CAROONA',
 'BATEMANS BAY',
 'THIRLMERE',
 'BINJURA',
 'BUNGOWANNAH',
 'CROWS NEST',
 'BERRIMA',
 'CHARMHAVEN',
 'GREENLANDS',
 'WESTELLA',
 'KOOTINGAL',
 'CASINO',
 'ALLEENA',
 'YARROWITCH',
 'DUNDEE',
 'BELLINGEN',
 'BERRIGAL',
 'BINDA',
 'UNANDERRA',
 'ELIZABETH BAY',
 'JEMALONG',
 'BUSBYS FLAT',
 'URANA',
 'NEWTON BOYD',
 'GUNNING',
 'WEE JASPER',
 'GEORGETOWN',
 'CHARLTON',
 'MELONBA',
 'GLOUCESTER',
 'NELSON BAY',
 'UPPER TAYLORS ARM',
 'DARLINGTON',
 'SYLVANIA',
 'TOOROOKA',
 'TERRAGON',
 'GUNNEDAH',
 'STEWARTS BROOK',
 'HANGING ROCK',
 'HEATHERBRAE',
 'COWABBIE',
 'TARRAWANNA',
 'GOONUMBLA',
 'ARKSTONE',
 'TABBITA',
 'FORBES',
 'GOOLMANGAR',
 'TULLOONA',
 'BEVENDALE',
 'SOMERTON',
 'BERESFIELD',
 'PLUMPTON',
 'VINEYARD',
 'HOLSWORTHY',
 'GREEN POINT',
 'CALIMO',
 'BUNDELLA',
 'BARMEDMAN',
 'ARIAH PARK',
 'BENDEMEER',
 'DARUKA',
 'MT RIVERS',
 'WADALBA',
 'COLO',
 'MALUA BAY',
 'WHERROL FLAT',
 'WOMBOOTA',
 'THE HILL',
 'BALD RIDGE',
 'LAMBTON',
 'TUNGLEBUNG',
 'MENDOORAN',
 'BEVERLEY PARK',
 'GINEROI',
 'PEMULWUY',
 'ARMATREE',
 'STRATFORD',
 'ARALUEN',
 'MURRAMI',
 'THE PONDS',
 'BANKSMEADOW',
 'KELSO',
 'OCEAN SHORES',
 'UPPER MACDONALD',
 'TENANDRA',
 'LIMEBURNERS CREEK',
 'CHIPPENDALE',
 'REDHEAD',
 'MARAYONG',
 'SOUTH GRANVILLE',
 'ELANDS',
 'SPRINGDALE HEIGHTS',
 'NORTH LAMBTON',
 'TALLIMBA',
 'LANKEYS CREEK',
 'SANDY HOLLOW',
 'CHAKOLA',
 'CASSILIS',
 'LOWER PORTLAND',
 'BREELONG',
 'SEAFORTH',
 'MANLY VALE',
 'FALLS CREEK',
 'BELLEVUE HILL',
 'CROWTHER',
 'ABERDARE',
 'ARKELL',
 'BINDERA',
 'DUNEDOO',
 'FRAZERS CREEK',
 'TOOLOOM',
 'BOGANGAR',
 'MELLOOL',
 'GLENFIELD PARK',
 'NIRIMBA FIELDS',
 'SOUTH MURWILLUMBAH',
 'MULLAMUDDY',
 'GOGELDRIE',
 'SPRING TERRACE',
 'DRAKE',
 'BIRGANBIGIL',
 'GRENFELL',
 'ARTARMON',
 'MOUNT DAVID',
 'UPPER EDEN CREEK',
 'TANILBA BAY',
 'TREWILGA',
 'MYRTLE CREEK',
 'SEVEN OAKS',
 'FERNSIDE',
 'TALLAWONG',
 'MYALL CREEK',
 'JACKY BULBIN FLAT',
 'BINALONG',
 'HILL END',
 'BANOON',
 'NERRIGA',
 'HUNTERVIEW',
 'TAMINDA',
 'ELDERSLIE',
 'MOGO CREEK',
 'MOUNT WHITE',
 'NANGUS',
 'WARRAH CREEK',
 'JINDERA',
 'TOMS CREEK',
 'BOONOO BOONOO',
 'BOBIN',
 'ABERDEEN',
 'CALOOLA',
 'PIALLAWAY',
 'SOUTH WENTWORTHVILLE',
 'BOOROWA',
 'SHANNON VALE',
 'PEELWOOD',
 'COOYAL',
 'GRONG GRONG',
 'BROWNS MOUNTAIN',
 'COLLENDINA',
 'RATHMINES',
 'RICHMOND',
 'BROKEN HILL',
 'LEGUME',
 'ROZELLE',
 'BINGARA',
 'WIAGDON',
 'ATTUNGA',
 'LOCKHART',
 'BULGA FOREST',
 'NERONG',
 'JUNEE',
 'COLLARENEBRI',
 'LEICHHARDT',
 'QUEENSCLIFF',
 'FULLERTON',
 'BOOKHAM',
 'RIVERTREE',
 'GLEN ALLEN',
 'TARRO',
 'GUNBAR',
 'ROSEVILLE',
 'LAKE HEIGHTS',
 'MAYBOLE',
 'GURRANANG',
 'LAWRENCE',
 'HOLLISDALE',
 'BROULEE',
 'SYLVANIA WATERS',
 'KLORI',
 'COPETON',
 'BLAKNEY CREEK',
 'BALMORAL',
 'MOUNT WARNING',
 'EUNGELLA',
 'LIMBRI',
 'GLENDON BROOK',
 'WARRAGOON',
 'MAYFIELD EAST',
 'MANILDRA',
 'NARARA',
 'KANGAROO CREEK',
 'BUGALDIE',
 'GOORANGOOLA',
 'BENDICK MURRELL',
 'PORTLAND',
 'DEBENHAM',
 'UPPER NILE',
 'BOOKER BAY',
 'CELLS RIVER',
 'COXS CREEK',
 'UPPER MANILLA',
 'BELLBROOK',
 'JERANGLE',
 'CALAMIA',
 'BROADMEADOW',
 'CARRATHOOL',
 'CARINDA',
 'LISTON',
 'BUNNALOO',
 'MALLAN',
 'HAYMARKET',
 'OOTHA',
 'TAREN POINT',
 'BONSHAW',
 'LEWISHAM',
 'MARYVALE',
 'WOOLWICH',
 'MORUNDAH',
 'WYANBENE',
 'YAMBA',
 'BOX HILL',
 'TRANGIE',
 'CLEAR RANGE',
 'HAYWARDS BAY',
 'PEAK HILL',
 'YAOUK',
 'WARRANULLA',
 'NIMMITABEL',
 'CALIFAT',
 'CROOKED CORNER',
 'BARA',
 'BIRMINGHAM GARDENS',
 'BOAT HARBOUR',
 'BOWRAL',
 'KIPPENDUFF',
 'BOSSLEY PARK',
 'MARLEE',
 'SHELLHARBOUR',
 'UPPER MONGOGARIE',
 'WOOLLAHRA',
 'SANDRINGHAM',
 'GLENUGIE',
 'SINGLETON',
 'YOWRIE',
 'BROGO',
 'BOGEE',
 'NORTH SYDNEY',
 'FRENCHS FOREST',
 'WYANGALA',
 'TINPOT',
 'EUNGAI RAIL',
 'CATHERINE FIELD',
 'BOOROLONG',
 ...]

In [43]:
ttd[ttd.suburb.isin(['BAULKHAM HILLS'])]

,property_id,house_number,street_name,suburb,postcode,area,area_unit,contract_date,settlement_date,sale_price,zone,property_type,lot_description,source_week,year
1345031,2857138,56,DOBSON CRES,BAULKHAM HILLS,2153,142.0,M,2020-11-11,2021-01-15,720000.0,,RESIDENCE,26/SP65038,20210125,2021.0
1351668,4305386,41,YATTENDEN CRES,BAULKHAM HILLS,2153,113.0,M,2019-10-18,2021-01-25,712500.0,,RESIDENCE,37/SP101706,20210201,2021.0
1361312,3910851,52,OLD NORTHERN RD,BAULKHAM HILLS,2153,104.0,M,2021-01-11,2021-02-09,645000.0,,RESIDENCE,21/SP93007,20210215,2021.0
1372703,4170348,10,MERYLL AVE,BAULKHAM HILLS,2153,147.0,M,2021-01-14,2021-03-03,665000.0,,RESIDENCE,19/SP98628,20210308,2021.0
1377295,4170348,10,MERYLL AVE,BAULKHAM HILLS,2153,137.0,M,2021-02-16,2021-03-05,650000.0,,RESIDENCE,24/SP98628,20210315,2021.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2436685,3965941,1,MERYLL AVE,BAULKHAM HILLS,2153,120.0,M,2026-01-08,2026-02-06,620000.0,,RESIDENCE,18/SP94168,20260216,2026.0
2439077,3899569,13,SEVEN HILLS RD,BAULKHAM HILLS,2153,122.0,M,2026-01-12,2026-02-19,535000.0,,RESIDENCE,85/SP92307,20260223,2026.0
2469073,2857138,56,OLD NORTHERN RD,BAULKHAM HILLS,2153,128.0,M,2026-03-07,2026-04-20,765000.0,,RESIDENCE,31/SP65038,20260427,2026.0
2469085,3965941,1,MERYLL AVE,BAULKHAM HILLS,2153,119.0,M,2026-03-13,2026-04-17,706500.0,,RESIDENCE,12/SP94168,20260427,2026.0
2476650,3965941,1,MERYLL AVE,BAULKHAM HILLS,2153,122.0,M,2026-03-24,2026-05-04,673000.0,,RESIDENCE,144/SP94168,20260511,2026.0

In [16]:
df[df.property_type == 'UNIT'].property_id.unique()

<ArrowStringArray>
['3799290', '2041132', '3170728', '3804085',  '949929', '3157401',  '239939',
 '2989711', '1188650', '1938871',
 ...
 '3675674', '2567045',  '785907', '1612563',  '241523', '1117371', '3045692',
 '2320118',  '310547', '1821219']
Length: 824, dtype: str